### ISSUE TITLE
FluidLite is not used

### ISSUE THREAD

**Issue by Woyten** [katyo/fluidlite-rs#7]
Hi, thanks for the great bindings library!

FluidSynth works without any problems. However, I have a problem / question: If I understand the documentation correctly the "builtin" feature should replace FluidSynth with FluidLite. But when I use `features = ["builitin"]` it still seems to use FluidSynth.

For example, I get the error message "No tuning at bank 0, prog 0". The error message is expected but it cannot see it being declared in FluidLite s.t. I suspect it comes from FluidSynth.

**Comment by katyo** [comment]
@Woyten, thanks for your interest to this crate!

As you can see in README and docs this bindings to _FluidLite_ library not _FluidSynth_ which is not supported by this crate.
The `builtin` feature forces compiling builtin static FluidLite library even if system-wide FluidLite library found.
The error message "No tuning at bank 0, prog 0" is declared by FluidLite too (see [fluid_synth.c:3006](/divideconcept/FluidLite/blob/37e812d31d9f6b712e4385f6134084b5803a74a3/src/fluid_synth.c#L3006))

**Comment by Woyten** [comment]
@katyo Thanks for your explanation. I was on the wrong track for a couple of days. The reason: I had a checkout of FluidSynyth but I named the folder *FluidLite*. :facepalm:
I will close this issue since everything works as expected.
